@startuml
class Frogdrick{
+moverarriba()
+moverizquierda()
+moverderecha()
+moverabajo()
}
class Jugador
class Carro
class Plataforma
class Pasto
class Calle
class Escenario
class Obstaculo


Frogdrick *-- Vida
Jugador o-- Frogdrick
Jugador *-- Tiempo
Jugador *-- Puntos
Escenario *-- Plataforma
Escenario *-- Obstaculo
Obstaculo --|> Carro
Plataforma --|> Pasto
Plataforma --|> Calle
Frogdrick o-- Escenario
@enduml